#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5'
		let name++
	done
}
workspaces

bspc config border_width 0
bspc config window_gap 10
bspc config border_radius 15
bspc config split_ratio 0.50

# Colors
bspc config focused_border_color \#c0caf5
bspc config normal_border_color \#c0caf5
bspc config active_border_color \#c0caf5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false

bspc config external_rules_command "$HOME/.config/bspwm/scripts/external-rules"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Rofi state=floating
bspc rule -a Plank manage=off border=off locked=on focus=off follow=off layer=above

fcitx5 &
picom &
dunst &
udiskie &
jgmenu &
xfce4-power-manager &
redshift-gtk &
xsetroot -cursor_name left_ptr &
spotifyd --config-path $HOME/.config/spotifyd/spotifyd.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/geoclue-2.0/demos/agent &
feh --bg-scale ~/.wallpapers/tokyo.png

bash $HOME/.config/polybar/run.sh
bash $HOME/.config/bspwm/scripts/fix-plank
